---
title: "MetaG-heatmap-Binder"
subtitle: "This time use only RMarkdown file as input"
author: "Laetitia, Marian, Guillaume, and Charles"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output:
  html_document: 
    df_print: paged
    number_sections: yes
    toc: yes
    toc_float: true
    toc_depth: 3
    code_folding: show
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Load Libraries

```{r load-libraries}
library(tibble)
library(magrittr)
library(gplots)
library(dplyr)
```


# Relative Abundance data

Rel Abund = (Sum of Contig count)/(QC sequence abundace)

```{r heatmap-generation, fig.height=10, fig.width=12}
# Load in the dataframe of relative abundances
MAGnum_df <- read.delim("input_matrix_v2.txt") %>%
    tibble::column_to_rownames(var = "X")

# Transform the data to a matrix
MAGnum_mat <- MAGnum_df %>%
    data.matrix()

# Sample Metadata
metadat <- 
  read.table("Sample_metadata.txt", sep = "\t", header = TRUE) %>%
  mutate(colors = ifelse(Location == "Alaska", "cornflowerblue",
                         ifelse(Location == "Bodega Bay", "red",
                                ifelse(Location == "Japan North", "darkorchid",
                                       ifelse(Location == "Japan South", "darkorchid1",
                                              ifelse(Location == "Massachusetts", "deeppink",
                                                     ifelse(Location == "North Carolina", "darkslategray3",
                                                            ifelse(Location == "Quebec", "darkorange",
                                                                   ifelse(Location == "San Diego", "green4",
                                                                          ifelse(Location == "Washington", "ivory4",
                                                                                 ifelse(Location == "Norway", "firebrick",
                                                                                        ifelse(Location == "Sweden", "dodgerblue4",
                                                                                               ifelse(Location == "Wales", "gold2",
                                                                                                      ifelse(Location == "Portugal", "forestgreen",
                                                                                                             ifelse(Location == "French Med", "deepskyblue",
                                                                                                                    ifelse(Location == "Croatia", "firebrick1",
                                                                                                                                  NA))))))))))))))))


# Set the color pallette 
my_palette <- colorRampPalette(c("red","white ", "blue"))(n = 299)

# Set the colors of the different columns going in
colz <- metadat$colors

# Without any scaling 
heatmap.2(MAGnum_mat, 
          main = "Relative Abundance Data",
          distfun = function(x) dist(x, method = "euclidean"),
          hclustfun = function(x) hclust(x,method = "complete"),
          scale = "row",
          col = my_palette,
          trace = "none",
          ColSideColors = colz,
          key = TRUE, symkey = FALSE, 
          density.info = "none", srtCol = 30,
          margins=c(5.5,7), cexRow = 1.25, cexCol = 1.25,
          key.xlab = "MAG Abundance",
          lhei = c(1.5,9), 
          key.title=NA)

legend(y=0.75, x=-0.15, 
       xpd=TRUE,     
       legend = unique(metadat$Location),
       col = unique(metadat$colors), 
       lty= 1, lwd = 5, cex=.7)


# WITH scaling 
heatmap.2(MAGnum_mat, 
          main = "Scaled Relative Abundance Data",
          distfun = function(x) dist(x, method = "euclidean"),
          hclustfun = function(x) hclust(x,method = "complete"),
          scale = "row",
          col = my_palette,
          trace = "none",
          key = TRUE, symkey = FALSE, 
          density.info = "none", srtCol = 30,
          margins=c(5.5,7), cexRow = 1.25, cexCol = 1.25,
          key.xlab = "MAG Abundance",
          lhei = c(1.5,9), 
          key.title=NA)
```



# Normalize

## INSERT GUILLAUME DATA


# Abundance threshold cutoffs


## MAGs an average 0.1% and above
```{r}
abundant_mags <- MAGnum_mat[rowMeans(MAGnum_mat) > 0.001, ]
```



