---
title: "MetaG-heatmap-Binder"
subtitle: "This time use only RMarkdown file as input"
author: "Laetitia and Charles and Marian and Guillaume"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output:
  html_document: 
    df_print: paged
    number_sections: yes
    toc: yes
    toc_float: true
    toc_depth: 3
    code_folding: show
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# System Info

```{r}
# session info
sessionInfo()
```

# Load Libraries
```{r load-libraries}
library(tibble)
library(magrittr)
library(gplots)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(DT)
```

# Load Data
```{r data-loading}
# Read in all the data
# Rel Abund = (Sum of Contig count)/(QC sequence abundace)
MAGnum_df <- read.delim("input_matrix_v2.txt") %>%
    tibble::column_to_rownames(var = "X")

MAGnum_mat <- MAGnum_df %>%
    data.matrix()

MAGnum_count <- read.table("input_matrix_v1.counts.txt", sep="\t", header=TRUE)
rownames(MAGnum_count) <- MAGnum_count[,1]
MAGnum_count<-MAGnum_count[,-1]
head(MAGnum_count)

# read in the Bin stats
bin_stats <- read.table("bin_stats.txt", sep="\t", header=TRUE);
rownames(bin_stats)<-bin_stats[,1]
bin_stats<- bin_stats[,-1]

# Select the Top X abundance bins
abundant_mags <- MAGnum_mat[rowMeans(MAGnum_mat) > 0.0001, ]

# read in the Sample metadata 
# Add a new column with color information for plotting
metadat <- 
  read.table("Sample_metadata.txt", sep = "\t", header = TRUE) %>%
  mutate(colors = ifelse(Location == "Alaska", "cornflowerblue",
                         ifelse(Location == "Bodega Bay", "red",
                                ifelse(Location == "Japan North", "darkorchid",
                                       ifelse(Location == "Japan South", "darkorchid1",
                                              ifelse(Location == "Massachusetts", "deeppink",
                                                     ifelse(Location == "North Carolina", "darkslategray3",
                                                            ifelse(Location == "Quebec", "darkorange",
                                                                   ifelse(Location == "San Diego", "green4",
                                                                          ifelse(Location == "Washington", "ivory4",
                                                                                 ifelse(Location == "Norway", "firebrick",
                                                                                        ifelse(Location == "Sweden", "dodgerblue4",
                                                                                               ifelse(Location == "Wales", "gold2",
                                                                                                      ifelse(Location == "Portugal", "forestgreen",
                                                                                                             ifelse(Location == "French Med", "deepskyblue",
                                                                                                                    ifelse(Location == "Croatia", "black",
                                                                                                                                  NA))))))))))))))))

# Set the colors of the different columns going in
colz <- metadat$colors

location_colors <- c(
  Alaska = "cornflowerblue",
  "Bodega Bay" = "red",
  "Japan North" = "darkorchid",
  "Japan South" = "darkorchid1",
  Massachusetts = "deeppink",
  "North Carolina" = "darkslategray3",
  Quebec = "darkorange",
  "San Diego" =  "green4",
  Washington = "ivory4",
  Norway = "firebrick",
  Sweden = "dodgerblue4",
  Wales = "gold2",
  Portugal = "forestgreen",
  "French Med" = "deepskyblue",
  Croatia = "black")

# Set the color palette
my_palette <- colorRampPalette(c("red","white ", "blue"))(n = 299)
```

# Normalization
```{r data-normalized, fig.height=10, fig.width=12}
# Normalizing the matrix 
# Dividing rows by the genome size for the bin
# Genome size is different from Bin size
# Genome size is BinSize * BinCompletion

# Calculate the genome size
genome_sizes<- bin_stats$size * bin_stats$SCG_completeness

# Do the normalization
MAGnum_norm<-t(t(MAGnum_count) / genome_sizes)
```


# Plot
## Raw relative abundance data
```{r heatmap-relativeAbundance-1, fig.height=10, fig.width=12}
# Without any scaling 
heatmap.2(MAGnum_mat, 
          main = "NOT scaled Relative Abundance Data",
          distfun = function(x) dist(x, method = "euclidean"),
          hclustfun = function(x) hclust(x,method = "complete"),
          #scale = "row",
          col = my_palette,
          trace = "none",
          ColSideColors = colz,
          key = TRUE, symkey = FALSE, 
          density.info = "none", srtCol = 30,
          margins=c(5.5,7), cexRow = 1.25, cexCol = 1.25,
          key.xlab = "MAG Abundance",
          lhei = c(1.5,9), 
          key.title=NA)

# Add legend
legend(y=0.75, x=0.05, 
       xpd=TRUE,     
       legend = unique(metadat$Location),
       col = unique(metadat$colors), 
       lty= 1, lwd = 5, cex=.7)
```

## Scaled relative abundance
```{r heatmap-relativeAbundance-2, fig.height=10, fig.width=12}
heatmap.2(MAGnum_mat, 
          main="Relative abundance scaled",
        distfun = function(x) dist(x, method = "euclidean"),
        hclustfun = function(x) hclust(x,method = "complete"),
        scale = "row",
        col = my_palette, 
        trace = "none",
        key = TRUE, symkey = FALSE, 
        density.info = "none", srtCol = 30,
        margins=c(5.5,7), cexRow = 1.25,cexCol = 1.25,
        key.xlab = "MAG Abundance",
        lhei = c(1.5,9), 
        key.title=NA,
        ColSideColors = colz)

# Add legend
legend(y=0.75, x=0.05, 
       xpd=TRUE,     
       legend = unique(metadat$Location),
       col = unique(metadat$colors), 
       lty= 1, lwd = 5, cex=.7)
```



## Scaled normalized data
### Counts per Bin Per sample divided by genome size
```{r heatmap-normalized-scaled, fig.height=10, fig.width=12}

# WITH scaling 
heatmap.2(MAGnum_norm, 
          main = "Scaled Normalized Data",
          distfun = function(x) dist(x, method = "euclidean"),
          hclustfun = function(x) hclust(x,method = "complete"),
          scale = "row",
          col = my_palette,
          trace = "none",
          key = TRUE, symkey = FALSE, 
          density.info = "none", srtCol = 30,
          margins=c(5.5,7), cexRow = 1.25, cexCol = 1.25,
          key.xlab = "MAG Abundance",
          lhei = c(1.5,9), 
          key.title=NA,
          ColSideColors = colz)

# Add legend
legend(y=0.75, x=0.05, 
       xpd=TRUE,     
       legend = unique(metadat$Location),
       col = unique(metadat$colors), 
       lty= 1, lwd = 5, cex=.7)
```


## Scaled Meanm Abundance MAGs > 0.0001 
```{r heatmap-TopX-NOTscaled, fig.height=10, fig.width=12}
# WITH scaling 
heatmap.2(abundant_mags, 
          main = "Scaled Mean Top Abundant MAGs",
          distfun = function(x) dist(x, method = "euclidean"),
          hclustfun = function(x) hclust(x,method = "complete"),
          scale = "row",
          col = my_palette,
          trace = "none",
          key = TRUE, symkey = FALSE, 
          density.info = "none", srtCol = 30,
          margins=c(5.5,7), cexRow = 1.25, cexCol = 1.25,
          key.xlab = "MAG Abundance",
          lhei = c(1.5,9), 
          key.title=NA,
          ColSideColors = colz)

legend(y=0.75, x=0.05, 
       xpd=TRUE,     
       legend = unique(metadat$Location),
       col = unique(metadat$colors), 
       lty= 1, lwd = 5, cex=.7)

```



# Top MAG Abundance Plot

```{r abundance-plots, fig.width=10, fig.height=8}
# Select the Top X abundance bins
top_mags <- 
  MAGnum_mat[rowMeans(MAGnum_mat) > 0.001, ]

# How many MAGs?
num_MAGs <- nrow(top_mags)

# Prepare dataframe for plotting
abund_df <- top_mags %>%
  t() %>%
  as.data.frame() %>%
  tibble::rownames_to_column(var = "MAG") %>%
  rename(Sample = MAG) %>%
  gather("MAG", "norm_abund", 2:(num_MAGs+1)) %>%
  left_join(metadat, by = "Sample") %>%
  dplyr::select(-colors) 

# What's the data frame look like?
datatable(abund_df, options = list(pageLength = 10))

# Plot each MAG by location
MAG_abund_plot <- 
  ggplot(abund_df, 
       aes(x = Location, y = norm_abund, color = Location, fill = Location)) + 
  geom_jitter() + 
  #geom_boxplot(alpha = 0.4, outlier.shape = NA) + 
  theme_minimal() + 
  scale_color_manual(values = location_colors) +
  scale_fill_manual(values = location_colors) +
  facet_wrap(~MAG, scales = "free") +
  labs(y = "Normalized MAG Abundance") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1))

# Interactive Plot 
ggplotly(MAG_abund_plot) # Make the plot interactive
```

